spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/mono
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

gemini:
  base-url: ${GEMINI_BASE_URL}

googleai:
  api:
    key: ${GEMINI_API_KEY}