spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: ${AWS_JWT_SECRET_KEY}

gemini:
  base-url: ${AWS_GEMINI_BASE_URL}

googleai:
  api:
    key: ${AWS_GEMINI_API_KEY}