spring:
  application:
    name: mono

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: default
    password: default
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

gemini:
  base-url: ${GEMINI_BASE_URL}

googleai:
  api:
    key: ${GEMINI_API_KEY}